# Активный диалект: postgres | firebird
db.dialect=postgres

# PostgreSQL пример
db.url=jdbc:postgresql://localhost:5432/scp_foundation
db.user=scp_admin
db.password=changeme

# Firebird пример (раскомментируйте и закомментируйте Postgres):
# db.dialect=firebird
# db.url=jdbc:firebirdsql://localhost:3050/C:/firebird/scp_foundation.fdb
# db.user=SYSDBA
# db.password=masterkey
